# Generated by Django 5.0.1 on 2024-02-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smscode',
            old_name='code',
            new_name='pin',
        ),
    ]
