# Generated by Django 5.0.1 on 2024-02-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_code_smscode_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscode',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
